### ISSUE TITLE
Error with "./utils/build-cython.sh"

### ISSUE THREAD

**Issue by petteriTeikari** [hfawaz/aaltd18#1]
Thanks a lot for providing the code for this data augmentation, and for the time series benchmarking :)

I could not get your Cython build to go through as you were probably missing [these lines from your setup.py](https://stackoverflow.com/questions/14657375/cython-fatal-error-numpy-arrayobject-h-no-such-file-or-directory), as I got this error:

```python
dtw.c:579:10: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

I changed your `setup.py` to this, and it seems to be working:

```python
from distutils.core import setup
from Cython.Build import cythonize
import numpy

setup(
      ext_modules=cythonize("dtw.pyx"),
      include_dirs=[numpy.get_include()]
)
```

**Comment by hfawaz** [comment]
Hello, 

Thank you for sharing the problem. 

I think this has to do with python environments or maybe with API versions because for it is working properly. 

But anyone who encounter an error with Cython should try your suggestion which is why I labeled the issue as "good first issue" !! 

Do not hesitate if you have more questions and good luck !!
